#!/usr/bin/env bash
# Generate rotated Quilore secrets. Never prints secret values in dry-run summaries
# beyond length/fingerprint metadata.
set -euo pipefail

usage() {
  cat <<'EOF'
Usage: rotate-secrets.sh (--dry-run|--apply) [--out <path>]

Creates a new secrets.env with rotated JWT_SECRET and DATA_ENCRYPTION_KEY.
Provider API keys are listed for manual rotation (external consoles).
EOF
}

MODE=""
OUT="${HOME}/.quilore/secrets.env"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --dry-run) MODE="dry-run"; shift ;;
    --apply) MODE="apply"; shift ;;
    --out) OUT="${2:-}"; shift 2 ;;
    -h|--help) usage; exit 0 ;;
    *) echo "Unknown argument: $1" >&2; usage >&2; exit 2 ;;
  esac
done

if [[ -z "$MODE" ]]; then
  echo "error: --dry-run or --apply is required" >&2
  exit 2
fi

if [[ "$OUT" == *"/workspace/"* ]] || [[ "$OUT" == /workspace* ]]; then
  echo "error: refusing to write secrets inside the git workspace: $OUT" >&2
  exit 2
fi

jwt_secret() {
  openssl rand -base64 48 | tr -d '\n'
}

data_key() {
  openssl rand -base64 32 | tr -d '\n'
}

fingerprint() {
  # Short non-reversible fingerprint for logs / dry-run output
  printf '%s' "$1" | openssl dgst -sha256 | awk '{print substr($2,1,12)}'
}

JWT="$(jwt_secret)"
DATA_KEY="$(data_key)"

echo "Secret rotation plan mode=${MODE}"
echo "  JWT_SECRET length=${#JWT} fingerprint=$(fingerprint "$JWT")"
echo "  DATA_ENCRYPTION_KEY length=${#DATA_KEY} fingerprint=$(fingerprint "$DATA_KEY")"
echo "  Manual provider rotations required: GROQ_API_KEY OPENROUTER_API_KEY HF_API_TOKEN NVIDIA_NIM_API_KEY"
echo "  Re-encrypt hook: schedule field re-encryption before discarding previous DATA_ENCRYPTION_KEY"

if [[ "$MODE" == "dry-run" ]]; then
  echo "dry-run complete — no secrets file written"
  exit 0
fi

mkdir -p "$(dirname "$OUT")"
umask 077
cat > "$OUT" <<EOF
# Generated by rotate-secrets.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# DO NOT COMMIT
JWT_SECRET=${JWT}
DATA_ENCRYPTION_KEY=${DATA_KEY}
EOF
chmod 600 "$OUT"
echo "Wrote secrets to ${OUT} (mode 600)"
echo "Next: load into the deployment environment and restart services over TLS."
